name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enable manual triggering

jobs:
  staging-deploy:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      env: "staging"
    secrets: inherit
  
  production-deploy:
    needs: staging-deploy
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      env: "production"
    secrets: inherit
  