name: Development Workflow

on:
  push:
    branches:
      - dev

jobs:
  get-secret-from-environment-secret:
    runs-on: ubuntu-latest
    environment: sandbox
    outputs:
      AWS_ACCESS_KEY_ID: ${{ steps.set-secrets.outputs.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ steps.set-secrets.outputs.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ steps.set-secrets.outputs.AWS_DEFAULT_REGION }}
      EC2_TAG_NAME: ${{ steps.set-secrets.outputs.EC2_TAG_NAME }}
      EC2_TAG_VALUE: ${{ steps.set-secrets.outputs.EC2_TAG_VALUE }}
      EC2_USER: ${{ steps.set-secrets.outputs.EC2_USER }}
      EC2_SSH_KEY: ${{ steps.set-secrets.outputs.EC2_SSH_KEY }}   
    steps:
      - name: Set Multiple Secrets to GITHUB_OUTPUT
        id: set-secrets
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_OUTPUT
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_OUTPUT
          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> $GITHUB_OUTPUT
          echo "EC2_TAG_NAME=${{ secrets.EC2_TAG_NAME }}" >> $GITHUB_OUTPUT
          echo "EC2_TAG_VALUE=${{ secrets.EC2_TAG_VALUE }}" >> $GITHUB_OUTPUT
          echo "EC2_USER=${{ secrets.EC2_USER }}" >> $GITHUB_OUTPUT
          echo "EC2_SSH_KEY=${{ secrets.EC2_SSH_KEY }}" >> $GITHUB_OUTPUT


  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    needs: get-secret-from-environment-secret
    with:
      my_env: "sandbox"
    secrets: inherit # Inherit all secrets from the Development Workflow