name: Development Workflow

on:
  push:
    branches:
      - dev

jobs:
  get-secret-from-environment-secret:
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - name: Set Multiple Secrets to GITHUB_ENV
        id: set-secrets
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> $GITHUB_ENV
          echo "EC2_TAG_NAME=${{ secrets.EC2_TAG_NAME }}" >> $GITHUB_ENV
          echo "EC2_TAG_VALUE=${{ secrets.EC2_TAG_VALUE }}" >> $GITHUB_ENV
          echo "EC2_USER=${{ secrets.EC2_USER }}" >> $GITHUB_ENV
          echo "EC2_SSH_KEY=${{ secrets.EC2_SSH_KEY }}" >> $GITHUB_ENV


  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    needs: get-secret-from-environment-secret
    with:
      my_env: "sandbox"
    secrets: inherit # Inherit all secrets from the Development Workflow